version: "3.7"

services:
  # ui:
  #   image: tolltaxcollectorui:latest
  #   ports:
  #     - 4200:3000
  #   build:
  #     context: .
  #     dockerfile: ./client/app.dockerfile
  #   depends_on:
  #     - graphql
  #   environment:
  #     GRAPH_URL: http://localhost:8000/graphql
  tolltax:
    image: tolltax:latest
    build:
      context: .
      dockerfile: ./tolltax/app.dockerfile
    depends_on:
      - tolltax_db
    environment:
      DATABASE_URL: postgres://boomshiva:123456@tolltax_db/tollcollector?sslmode=disable
      PAYMENT_SERVICE_URL: payment:8080
    restart: on-failure
  payment:
    image: payment:latest
    build:
      context: .
      dockerfile: ./payment/app.dockerfile
    depends_on:
      - tolltax
      - payment_db
    environment:
      DATABASE_URL: postgres://boomshiva:123456@payment_db/tollcollector?sslmode=disable
    restart: on-failure
  graphql:
    image: tolltaxcollectorgraph:latest
    build:
      context: .
      dockerfile: ./graphql/app.dockerfile
    ports:
      - 8000:8080
    depends_on:
      - tolltax
      - payment
    environment:
      TOLLTAX_SERVICE_URL: tolltax:8080
      PAYMENT_SERVICE_URL: payment:8080
    restart: on-failure
  tolltax_db:
    image: tolltaxdb:latest
    build:
      context: ./tolltax
      dockerfile: ./db.dockerfile
    environment:
      POSTGRES_DB: tollcollector
      POSTGRES_USER: boomshiva
      POSTGRES_PASSWORD: 123456
    restart: unless-stopped
  payment_db:
    image: paymentdb:latest
    build:
      context: ./tolltax
      dockerfile: ./db.dockerfile
    environment:
      POSTGRES_DB: tollcollector
      POSTGRES_USER: boomshiva
      POSTGRES_PASSWORD: 123456
    restart: unless-stopped
