version: "3.7"

services:
  tolltax:
    build:
      context: .
      dockerfile: ./tolltax/app.dockerfile
    depends_on:
      - tolltax_db
    environment:
      DATABASE_URL: postgres://boomshiva:123456@tolltax_db/tollcollector?sslmode=disable
    restart: on-failure

#  catalog:
#    build:
#      context: .
#      dockerfile: ./catalog/app.dockerfile
#    depends_on:
#      - catalog_db
#    environment:
#      DATABASE_URL: http://catalog_db:9200
#    restart: on-failure
#
#  order:
#    build:
#      context: .
#      dockerfile: ./order/app.dockerfile
#    depends_on:
#      - order_db
#    environment:
#      DATABASE_URL: postgres://spidey:123456@order_db/spidey?sslmode=disable
#      ACCOUNT_SERVICE_URL: account:8080
#      CATALOG_SERVICE_URL: catalog:8080
#    restart: on-failure
#
#  graphql:
#    build:
#      context: .
#      dockerfile: ./graphql/app.dockerfile
#    ports:
#      - 8000:8080
#    depends_on:
#      - account
#      - catalog
#    environment:
#      ACCOUNT_SERVICE_URL: account:8080
#      CATALOG_SERVICE_URL: catalog:8080
#      ORDER_SERVICE_URL: order:8080
#    restart: on-failure
#
  tolltax_db:
    build:
      context: ./tolltax
      dockerfile: ./db.dockerfile
    environment:
      POSTGRES_DB: tollcollector
      POSTGRES_USER: boomshiva
      POSTGRES_PASSWORD: 123456
    restart: unless-stopped
#
#  catalog_db:
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
#    environment:
#      ES_JAVA_OPTS: -Xms1g -Xmx1g
#      discovery.type: single-node
#
#  order_db:
#    build:
#      context: ./order
#      dockerfile: ./db.dockerfile
#    environment:
#      POSTGRES_DB: spidey
#      POSTGRES_USER: spidey
#      POSTGRES_PASSWORD: 123456
#    restart: unless-stopped
