// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.3
// source: tolltax.proto

package tolltaxpb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ACTION int32

const (
	ACTION_DEBIT  ACTION = 0
	ACTION_CREDIT ACTION = 1
)

// Enum value maps for ACTION.
var (
	ACTION_name = map[int32]string{
		0: "DEBIT",
		1: "CREDIT",
	}
	ACTION_value = map[string]int32{
		"DEBIT":  0,
		"CREDIT": 1,
	}
)

func (x ACTION) Enum() *ACTION {
	p := new(ACTION)
	*p = x
	return p
}

func (x ACTION) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ACTION) Descriptor() protoreflect.EnumDescriptor {
	return file_tolltax_proto_enumTypes[0].Descriptor()
}

func (ACTION) Type() protoreflect.EnumType {
	return &file_tolltax_proto_enumTypes[0]
}

func (x ACTION) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ACTION.Descriptor instead.
func (ACTION) EnumDescriptor() ([]byte, []int) {
	return file_tolltax_proto_rawDescGZIP(), []int{0}
}

type Owner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ownerid       int64  `protobuf:"varint,1,opt,name=ownerid,proto3" json:"ownerid,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Accountnumber int64  `protobuf:"varint,3,opt,name=accountnumber,proto3" json:"accountnumber,omitempty"`
}

func (x *Owner) Reset() {
	*x = Owner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tolltax_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Owner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Owner) ProtoMessage() {}

func (x *Owner) ProtoReflect() protoreflect.Message {
	mi := &file_tolltax_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Owner.ProtoReflect.Descriptor instead.
func (*Owner) Descriptor() ([]byte, []int) {
	return file_tolltax_proto_rawDescGZIP(), []int{0}
}

func (x *Owner) GetOwnerid() int64 {
	if x != nil {
		return x.Ownerid
	}
	return 0
}

func (x *Owner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Owner) GetAccountnumber() int64 {
	if x != nil {
		return x.Accountnumber
	}
	return 0
}

type Car struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Carid     int64  `protobuf:"varint,1,opt,name=carid,proto3" json:"carid,omitempty"`
	Make      string `protobuf:"bytes,2,opt,name=make,proto3" json:"make,omitempty"`
	Cartype   string `protobuf:"bytes,3,opt,name=cartype,proto3" json:"cartype,omitempty"`
	Carnumber string `protobuf:"bytes,4,opt,name=carnumber,proto3" json:"carnumber,omitempty"`
}

func (x *Car) Reset() {
	*x = Car{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tolltax_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Car) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Car) ProtoMessage() {}

func (x *Car) ProtoReflect() protoreflect.Message {
	mi := &file_tolltax_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Car.ProtoReflect.Descriptor instead.
func (*Car) Descriptor() ([]byte, []int) {
	return file_tolltax_proto_rawDescGZIP(), []int{1}
}

func (x *Car) GetCarid() int64 {
	if x != nil {
		return x.Carid
	}
	return 0
}

func (x *Car) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *Car) GetCartype() string {
	if x != nil {
		return x.Cartype
	}
	return ""
}

func (x *Car) GetCarnumber() string {
	if x != nil {
		return x.Carnumber
	}
	return ""
}

type Netc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fkownerid int64 `protobuf:"varint,1,opt,name=fkownerid,proto3" json:"fkownerid,omitempty"`
	Fkcarid   int64 `protobuf:"varint,2,opt,name=fkcarid,proto3" json:"fkcarid,omitempty"`
}

func (x *Netc) Reset() {
	*x = Netc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tolltax_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Netc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Netc) ProtoMessage() {}

func (x *Netc) ProtoReflect() protoreflect.Message {
	mi := &file_tolltax_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Netc.ProtoReflect.Descriptor instead.
func (*Netc) Descriptor() ([]byte, []int) {
	return file_tolltax_proto_rawDescGZIP(), []int{2}
}

func (x *Netc) GetFkownerid() int64 {
	if x != nil {
		return x.Fkownerid
	}
	return 0
}

func (x *Netc) GetFkcarid() int64 {
	if x != nil {
		return x.Fkcarid
	}
	return 0
}

type TollBooth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tollboothid   int64  `protobuf:"varint,1,opt,name=tollboothid,proto3" json:"tollboothid,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Accountnumber int64  `protobuf:"varint,3,opt,name=accountnumber,proto3" json:"accountnumber,omitempty"`
}

func (x *TollBooth) Reset() {
	*x = TollBooth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tolltax_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TollBooth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TollBooth) ProtoMessage() {}

func (x *TollBooth) ProtoReflect() protoreflect.Message {
	mi := &file_tolltax_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TollBooth.ProtoReflect.Descriptor instead.
func (*TollBooth) Descriptor() ([]byte, []int) {
	return file_tolltax_proto_rawDescGZIP(), []int{3}
}

func (x *TollBooth) GetTollboothid() int64 {
	if x != nil {
		return x.Tollboothid
	}
	return 0
}

func (x *TollBooth) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TollBooth) GetAccountnumber() int64 {
	if x != nil {
		return x.Accountnumber
	}
	return 0
}

type GenerateRFIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Netc *Netc `protobuf:"bytes,1,opt,name=netc,proto3" json:"netc,omitempty"`
}

func (x *GenerateRFIDRequest) Reset() {
	*x = GenerateRFIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tolltax_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateRFIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRFIDRequest) ProtoMessage() {}

func (x *GenerateRFIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tolltax_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRFIDRequest.ProtoReflect.Descriptor instead.
func (*GenerateRFIDRequest) Descriptor() ([]byte, []int) {
	return file_tolltax_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateRFIDRequest) GetNetc() *Netc {
	if x != nil {
		return x.Netc
	}
	return nil
}

type GenerateRFIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Rfid   string `protobuf:"bytes,2,opt,name=rfid,proto3" json:"rfid,omitempty"`
}

func (x *GenerateRFIDResponse) Reset() {
	*x = GenerateRFIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tolltax_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateRFIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRFIDResponse) ProtoMessage() {}

func (x *GenerateRFIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tolltax_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRFIDResponse.ProtoReflect.Descriptor instead.
func (*GenerateRFIDResponse) Descriptor() ([]byte, []int) {
	return file_tolltax_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateRFIDResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GenerateRFIDResponse) GetRfid() string {
	if x != nil {
		return x.Rfid
	}
	return ""
}

type ValidateRFIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rfid  string `protobuf:"bytes,1,opt,name=rfid,proto3" json:"rfid,omitempty"`
	Carid int64  `protobuf:"varint,2,opt,name=carid,proto3" json:"carid,omitempty"`
}

func (x *ValidateRFIDRequest) Reset() {
	*x = ValidateRFIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tolltax_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateRFIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRFIDRequest) ProtoMessage() {}

func (x *ValidateRFIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tolltax_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRFIDRequest.ProtoReflect.Descriptor instead.
func (*ValidateRFIDRequest) Descriptor() ([]byte, []int) {
	return file_tolltax_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateRFIDRequest) GetRfid() string {
	if x != nil {
		return x.Rfid
	}
	return ""
}

func (x *ValidateRFIDRequest) GetCarid() int64 {
	if x != nil {
		return x.Carid
	}
	return 0
}

type ValidateRFIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *ValidateRFIDResponse) Reset() {
	*x = ValidateRFIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tolltax_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateRFIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRFIDResponse) ProtoMessage() {}

func (x *ValidateRFIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tolltax_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRFIDResponse.ProtoReflect.Descriptor instead.
func (*ValidateRFIDResponse) Descriptor() ([]byte, []int) {
	return file_tolltax_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateRFIDResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type DeductRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount string `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Owner  *Owner `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (x *DeductRequest) Reset() {
	*x = DeductRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tolltax_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductRequest) ProtoMessage() {}

func (x *DeductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tolltax_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductRequest.ProtoReflect.Descriptor instead.
func (*DeductRequest) Descriptor() ([]byte, []int) {
	return file_tolltax_proto_rawDescGZIP(), []int{8}
}

func (x *DeductRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *DeductRequest) GetOwner() *Owner {
	if x != nil {
		return x.Owner
	}
	return nil
}

type DeductResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *DeductResponse) Reset() {
	*x = DeductResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tolltax_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductResponse) ProtoMessage() {}

func (x *DeductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tolltax_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductResponse.ProtoReflect.Descriptor instead.
func (*DeductResponse) Descriptor() ([]byte, []int) {
	return file_tolltax_proto_rawDescGZIP(), []int{9}
}

func (x *DeductResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type CreditRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount string     `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Booth  *TollBooth `protobuf:"bytes,2,opt,name=booth,proto3" json:"booth,omitempty"`
}

func (x *CreditRequest) Reset() {
	*x = CreditRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tolltax_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditRequest) ProtoMessage() {}

func (x *CreditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tolltax_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditRequest.ProtoReflect.Descriptor instead.
func (*CreditRequest) Descriptor() ([]byte, []int) {
	return file_tolltax_proto_rawDescGZIP(), []int{10}
}

func (x *CreditRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CreditRequest) GetBooth() *TollBooth {
	if x != nil {
		return x.Booth
	}
	return nil
}

type CreditResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *CreditResponse) Reset() {
	*x = CreditResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tolltax_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditResponse) ProtoMessage() {}

func (x *CreditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tolltax_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditResponse.ProtoReflect.Descriptor instead.
func (*CreditResponse) Descriptor() ([]byte, []int) {
	return file_tolltax_proto_rawDescGZIP(), []int{11}
}

func (x *CreditResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type CalculateAmountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cartype string `protobuf:"bytes,1,opt,name=cartype,proto3" json:"cartype,omitempty"`
}

func (x *CalculateAmountRequest) Reset() {
	*x = CalculateAmountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tolltax_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateAmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateAmountRequest) ProtoMessage() {}

func (x *CalculateAmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tolltax_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateAmountRequest.ProtoReflect.Descriptor instead.
func (*CalculateAmountRequest) Descriptor() ([]byte, []int) {
	return file_tolltax_proto_rawDescGZIP(), []int{12}
}

func (x *CalculateAmountRequest) GetCartype() string {
	if x != nil {
		return x.Cartype
	}
	return ""
}

type CalculateAmountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deducible int32 `protobuf:"varint,1,opt,name=deducible,proto3" json:"deducible,omitempty"`
}

func (x *CalculateAmountResponse) Reset() {
	*x = CalculateAmountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tolltax_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateAmountResponse) ProtoMessage() {}

func (x *CalculateAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tolltax_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateAmountResponse.ProtoReflect.Descriptor instead.
func (*CalculateAmountResponse) Descriptor() ([]byte, []int) {
	return file_tolltax_proto_rawDescGZIP(), []int{13}
}

func (x *CalculateAmountResponse) GetDeducible() int32 {
	if x != nil {
		return x.Deducible
	}
	return 0
}

type GetAllOwnersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner []*Owner `protobuf:"bytes,1,rep,name=owner,proto3" json:"owner,omitempty"`
}

func (x *GetAllOwnersResponse) Reset() {
	*x = GetAllOwnersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tolltax_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllOwnersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllOwnersResponse) ProtoMessage() {}

func (x *GetAllOwnersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tolltax_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllOwnersResponse.ProtoReflect.Descriptor instead.
func (*GetAllOwnersResponse) Descriptor() ([]byte, []int) {
	return file_tolltax_proto_rawDescGZIP(), []int{14}
}

func (x *GetAllOwnersResponse) GetOwner() []*Owner {
	if x != nil {
		return x.Owner
	}
	return nil
}

type GetAllOwnersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ref int32 `protobuf:"varint,1,opt,name=ref,proto3" json:"ref,omitempty"`
}

func (x *GetAllOwnersRequest) Reset() {
	*x = GetAllOwnersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tolltax_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllOwnersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllOwnersRequest) ProtoMessage() {}

func (x *GetAllOwnersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tolltax_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllOwnersRequest.ProtoReflect.Descriptor instead.
func (*GetAllOwnersRequest) Descriptor() ([]byte, []int) {
	return file_tolltax_proto_rawDescGZIP(), []int{15}
}

func (x *GetAllOwnersRequest) GetRef() int32 {
	if x != nil {
		return x.Ref
	}
	return 0
}

type CreateNewOwnerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Accountnumber int64  `protobuf:"varint,2,opt,name=accountnumber,proto3" json:"accountnumber,omitempty"`
}

func (x *CreateNewOwnerRequest) Reset() {
	*x = CreateNewOwnerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tolltax_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNewOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewOwnerRequest) ProtoMessage() {}

func (x *CreateNewOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tolltax_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewOwnerRequest.ProtoReflect.Descriptor instead.
func (*CreateNewOwnerRequest) Descriptor() ([]byte, []int) {
	return file_tolltax_proto_rawDescGZIP(), []int{16}
}

func (x *CreateNewOwnerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNewOwnerRequest) GetAccountnumber() int64 {
	if x != nil {
		return x.Accountnumber
	}
	return 0
}

type CreateNewOwnerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ownerid int64 `protobuf:"varint,1,opt,name=ownerid,proto3" json:"ownerid,omitempty"`
}

func (x *CreateNewOwnerResponse) Reset() {
	*x = CreateNewOwnerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tolltax_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNewOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewOwnerResponse) ProtoMessage() {}

func (x *CreateNewOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tolltax_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewOwnerResponse.ProtoReflect.Descriptor instead.
func (*CreateNewOwnerResponse) Descriptor() ([]byte, []int) {
	return file_tolltax_proto_rawDescGZIP(), []int{17}
}

func (x *CreateNewOwnerResponse) GetOwnerid() int64 {
	if x != nil {
		return x.Ownerid
	}
	return 0
}

type VehicleOwnerDetailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rfid   string `protobuf:"bytes,1,opt,name=rfid,proto3" json:"rfid,omitempty"`
	Action ACTION `protobuf:"varint,2,opt,name=action,proto3,enum=pb.ACTION" json:"action,omitempty"`
}

func (x *VehicleOwnerDetailsRequest) Reset() {
	*x = VehicleOwnerDetailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tolltax_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VehicleOwnerDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleOwnerDetailsRequest) ProtoMessage() {}

func (x *VehicleOwnerDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tolltax_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleOwnerDetailsRequest.ProtoReflect.Descriptor instead.
func (*VehicleOwnerDetailsRequest) Descriptor() ([]byte, []int) {
	return file_tolltax_proto_rawDescGZIP(), []int{18}
}

func (x *VehicleOwnerDetailsRequest) GetRfid() string {
	if x != nil {
		return x.Rfid
	}
	return ""
}

func (x *VehicleOwnerDetailsRequest) GetAction() ACTION {
	if x != nil {
		return x.Action
	}
	return ACTION_DEBIT
}

type TollBoothDetailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tollboothid int64  `protobuf:"varint,1,opt,name=tollboothid,proto3" json:"tollboothid,omitempty"`
	Action      ACTION `protobuf:"varint,2,opt,name=action,proto3,enum=pb.ACTION" json:"action,omitempty"`
}

func (x *TollBoothDetailsRequest) Reset() {
	*x = TollBoothDetailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tolltax_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TollBoothDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TollBoothDetailsRequest) ProtoMessage() {}

func (x *TollBoothDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tolltax_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TollBoothDetailsRequest.ProtoReflect.Descriptor instead.
func (*TollBoothDetailsRequest) Descriptor() ([]byte, []int) {
	return file_tolltax_proto_rawDescGZIP(), []int{19}
}

func (x *TollBoothDetailsRequest) GetTollboothid() int64 {
	if x != nil {
		return x.Tollboothid
	}
	return 0
}

func (x *TollBoothDetailsRequest) GetAction() ACTION {
	if x != nil {
		return x.Action
	}
	return ACTION_DEBIT
}

type VehicleOwnerDetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Accountnumber int64  `protobuf:"varint,2,opt,name=accountnumber,proto3" json:"accountnumber,omitempty"`
	Action        ACTION `protobuf:"varint,3,opt,name=action,proto3,enum=pb.ACTION" json:"action,omitempty"`
}

func (x *VehicleOwnerDetailsResponse) Reset() {
	*x = VehicleOwnerDetailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tolltax_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VehicleOwnerDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleOwnerDetailsResponse) ProtoMessage() {}

func (x *VehicleOwnerDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tolltax_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleOwnerDetailsResponse.ProtoReflect.Descriptor instead.
func (*VehicleOwnerDetailsResponse) Descriptor() ([]byte, []int) {
	return file_tolltax_proto_rawDescGZIP(), []int{20}
}

func (x *VehicleOwnerDetailsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VehicleOwnerDetailsResponse) GetAccountnumber() int64 {
	if x != nil {
		return x.Accountnumber
	}
	return 0
}

func (x *VehicleOwnerDetailsResponse) GetAction() ACTION {
	if x != nil {
		return x.Action
	}
	return ACTION_DEBIT
}

var File_tolltax_proto protoreflect.FileDescriptor

var file_tolltax_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x74, 0x6f, 0x6c, 0x6c, 0x74, 0x61, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0x5b, 0x0a, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x22, 0x67, 0x0a, 0x03, 0x43, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x61, 0x72, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6d, 0x61, 0x6b, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x6b,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x61, 0x72, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x61, 0x72, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x61, 0x72, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x3e, 0x0a, 0x04, 0x4e, 0x65, 0x74,
	0x63, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x6b, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x66, 0x6b, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x69, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x66, 0x6b, 0x63, 0x61, 0x72, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x66, 0x6b, 0x63, 0x61, 0x72, 0x69, 0x64, 0x22, 0x67, 0x0a, 0x09, 0x54, 0x6f, 0x6c,
	0x6c, 0x42, 0x6f, 0x6f, 0x74, 0x68, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x6c, 0x6c, 0x62, 0x6f,
	0x6f, 0x74, 0x68, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x6f, 0x6c,
	0x6c, 0x62, 0x6f, 0x6f, 0x74, 0x68, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x22, 0x33, 0x0a, 0x13, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x46,
	0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x04, 0x6e, 0x65, 0x74,
	0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x65, 0x74,
	0x63, 0x52, 0x04, 0x6e, 0x65, 0x74, 0x63, 0x22, 0x42, 0x0a, 0x14, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x52, 0x46, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x66, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x66, 0x69, 0x64, 0x22, 0x3f, 0x0a, 0x13, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x46, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x66, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x72, 0x66, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x61, 0x72, 0x69, 0x64, 0x22, 0x26, 0x0a, 0x14,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x46, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x02, 0x6f, 0x6b, 0x22, 0x48, 0x0a, 0x0d, 0x44, 0x65, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a,
	0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70,
	0x62, 0x2e, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x22, 0x20,
	0x0a, 0x0e, 0x44, 0x65, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b,
	0x22, 0x4c, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x05, 0x62, 0x6f, 0x6f,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x6f,
	0x6c, 0x6c, 0x42, 0x6f, 0x6f, 0x74, 0x68, 0x52, 0x05, 0x62, 0x6f, 0x6f, 0x74, 0x68, 0x22, 0x20,
	0x0a, 0x0e, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b,
	0x22, 0x32, 0x0a, 0x16, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x61,
	0x72, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x61, 0x72,
	0x74, 0x79, 0x70, 0x65, 0x22, 0x37, 0x0a, 0x17, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x64, 0x65, 0x64, 0x75, 0x63, 0x69, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x64, 0x65, 0x64, 0x75, 0x63, 0x69, 0x62, 0x6c, 0x65, 0x22, 0x37, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52,
	0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x22, 0x27, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x66, 0x22,
	0x51, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x4f, 0x77, 0x6e, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x22, 0x32, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x4f,
	0x77, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x69, 0x64, 0x22, 0x54, 0x0a, 0x1a, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c,
	0x65, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x66, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x72, 0x66, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x43,
	0x54, 0x49, 0x4f, 0x4e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x5f, 0x0a, 0x17,
	0x74, 0x6f, 0x6c, 0x6c, 0x42, 0x6f, 0x6f, 0x74, 0x68, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x6c, 0x6c, 0x62,
	0x6f, 0x6f, 0x74, 0x68, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x6f,
	0x6c, 0x6c, 0x62, 0x6f, 0x6f, 0x74, 0x68, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x06, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x41,
	0x43, 0x54, 0x49, 0x4f, 0x4e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x7b, 0x0a,
	0x1b, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x24, 0x0a, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x43, 0x54, 0x49,
	0x4f, 0x4e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2a, 0x1f, 0x0a, 0x06, 0x41, 0x43,
	0x54, 0x49, 0x4f, 0x4e, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x45, 0x42, 0x49, 0x54, 0x10, 0x00, 0x12,
	0x0a, 0x0a, 0x06, 0x43, 0x52, 0x45, 0x44, 0x49, 0x54, 0x10, 0x01, 0x32, 0xb6, 0x04, 0x0a, 0x0e,
	0x54, 0x6f, 0x6c, 0x6c, 0x54, 0x61, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43,
	0x0a, 0x0c, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x46, 0x49, 0x44, 0x12, 0x17,
	0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x46, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x46, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0c, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x46, 0x49, 0x44, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x46, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70,
	0x62, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x46, 0x49, 0x44, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x56, 0x0a, 0x19, 0x43, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x65, 0x44, 0x65, 0x64, 0x75, 0x63, 0x74, 0x69, 0x62, 0x6c, 0x65, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x43, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73,
	0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4f, 0x77, 0x6e, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5b, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x56, 0x65, 0x68, 0x69,
	0x63, 0x6c, 0x65, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12,
	0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x4f, 0x77, 0x6e, 0x65,
	0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x4f, 0x77, 0x6e, 0x65,
	0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x55, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6c, 0x6c, 0x42, 0x6f, 0x6f,
	0x74, 0x68, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x74,
	0x6f, 0x6c, 0x6c, 0x42, 0x6f, 0x6f, 0x74, 0x68, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x65, 0x68, 0x69,
	0x63, 0x6c, 0x65, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4e, 0x65, 0x77, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x74, 0x6f, 0x6c, 0x6c, 0x74, 0x61,
	0x78, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tolltax_proto_rawDescOnce sync.Once
	file_tolltax_proto_rawDescData = file_tolltax_proto_rawDesc
)

func file_tolltax_proto_rawDescGZIP() []byte {
	file_tolltax_proto_rawDescOnce.Do(func() {
		file_tolltax_proto_rawDescData = protoimpl.X.CompressGZIP(file_tolltax_proto_rawDescData)
	})
	return file_tolltax_proto_rawDescData
}

var file_tolltax_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tolltax_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_tolltax_proto_goTypes = []interface{}{
	(ACTION)(0),                         // 0: pb.ACTION
	(*Owner)(nil),                       // 1: pb.Owner
	(*Car)(nil),                         // 2: pb.Car
	(*Netc)(nil),                        // 3: pb.Netc
	(*TollBooth)(nil),                   // 4: pb.TollBooth
	(*GenerateRFIDRequest)(nil),         // 5: pb.GenerateRFIDRequest
	(*GenerateRFIDResponse)(nil),        // 6: pb.GenerateRFIDResponse
	(*ValidateRFIDRequest)(nil),         // 7: pb.ValidateRFIDRequest
	(*ValidateRFIDResponse)(nil),        // 8: pb.ValidateRFIDResponse
	(*DeductRequest)(nil),               // 9: pb.DeductRequest
	(*DeductResponse)(nil),              // 10: pb.DeductResponse
	(*CreditRequest)(nil),               // 11: pb.CreditRequest
	(*CreditResponse)(nil),              // 12: pb.CreditResponse
	(*CalculateAmountRequest)(nil),      // 13: pb.CalculateAmountRequest
	(*CalculateAmountResponse)(nil),     // 14: pb.CalculateAmountResponse
	(*GetAllOwnersResponse)(nil),        // 15: pb.GetAllOwnersResponse
	(*GetAllOwnersRequest)(nil),         // 16: pb.GetAllOwnersRequest
	(*CreateNewOwnerRequest)(nil),       // 17: pb.CreateNewOwnerRequest
	(*CreateNewOwnerResponse)(nil),      // 18: pb.CreateNewOwnerResponse
	(*VehicleOwnerDetailsRequest)(nil),  // 19: pb.VehicleOwnerDetailsRequest
	(*TollBoothDetailsRequest)(nil),     // 20: pb.tollBoothDetailsRequest
	(*VehicleOwnerDetailsResponse)(nil), // 21: pb.VehicleOwnerDetailsResponse
}
var file_tolltax_proto_depIdxs = []int32{
	3,  // 0: pb.GenerateRFIDRequest.netc:type_name -> pb.Netc
	1,  // 1: pb.DeductRequest.owner:type_name -> pb.Owner
	4,  // 2: pb.CreditRequest.booth:type_name -> pb.TollBooth
	1,  // 3: pb.GetAllOwnersResponse.owner:type_name -> pb.Owner
	0,  // 4: pb.VehicleOwnerDetailsRequest.action:type_name -> pb.ACTION
	0,  // 5: pb.tollBoothDetailsRequest.action:type_name -> pb.ACTION
	0,  // 6: pb.VehicleOwnerDetailsResponse.action:type_name -> pb.ACTION
	5,  // 7: pb.TollTaxService.GenerateRFID:input_type -> pb.GenerateRFIDRequest
	7,  // 8: pb.TollTaxService.ValidateRFID:input_type -> pb.ValidateRFIDRequest
	13, // 9: pb.TollTaxService.CalculateDeductibleAmount:input_type -> pb.CalculateAmountRequest
	16, // 10: pb.TollTaxService.GetAllOwners:input_type -> pb.GetAllOwnersRequest
	19, // 11: pb.TollTaxService.GetVehicleOwnerDetails:input_type -> pb.VehicleOwnerDetailsRequest
	20, // 12: pb.TollTaxService.GetTollBoothDetails:input_type -> pb.tollBoothDetailsRequest
	17, // 13: pb.TollTaxService.CreateNewOwner:input_type -> pb.CreateNewOwnerRequest
	6,  // 14: pb.TollTaxService.GenerateRFID:output_type -> pb.GenerateRFIDResponse
	8,  // 15: pb.TollTaxService.ValidateRFID:output_type -> pb.ValidateRFIDResponse
	14, // 16: pb.TollTaxService.CalculateDeductibleAmount:output_type -> pb.CalculateAmountResponse
	15, // 17: pb.TollTaxService.GetAllOwners:output_type -> pb.GetAllOwnersResponse
	21, // 18: pb.TollTaxService.GetVehicleOwnerDetails:output_type -> pb.VehicleOwnerDetailsResponse
	21, // 19: pb.TollTaxService.GetTollBoothDetails:output_type -> pb.VehicleOwnerDetailsResponse
	18, // 20: pb.TollTaxService.CreateNewOwner:output_type -> pb.CreateNewOwnerResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_tolltax_proto_init() }
func file_tolltax_proto_init() {
	if File_tolltax_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tolltax_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Owner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tolltax_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Car); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tolltax_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Netc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tolltax_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TollBooth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tolltax_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateRFIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tolltax_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateRFIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tolltax_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateRFIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tolltax_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateRFIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tolltax_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeductRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tolltax_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeductResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tolltax_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreditRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tolltax_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreditResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tolltax_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculateAmountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tolltax_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculateAmountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tolltax_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllOwnersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tolltax_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllOwnersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tolltax_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNewOwnerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tolltax_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNewOwnerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tolltax_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VehicleOwnerDetailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tolltax_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TollBoothDetailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tolltax_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VehicleOwnerDetailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tolltax_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tolltax_proto_goTypes,
		DependencyIndexes: file_tolltax_proto_depIdxs,
		EnumInfos:         file_tolltax_proto_enumTypes,
		MessageInfos:      file_tolltax_proto_msgTypes,
	}.Build()
	File_tolltax_proto = out.File
	file_tolltax_proto_rawDesc = nil
	file_tolltax_proto_goTypes = nil
	file_tolltax_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TollTaxServiceClient is the client API for TollTaxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TollTaxServiceClient interface {
	// Implemented
	GenerateRFID(ctx context.Context, in *GenerateRFIDRequest, opts ...grpc.CallOption) (*GenerateRFIDResponse, error)
	ValidateRFID(ctx context.Context, in *ValidateRFIDRequest, opts ...grpc.CallOption) (*ValidateRFIDResponse, error)
	CalculateDeductibleAmount(ctx context.Context, in *CalculateAmountRequest, opts ...grpc.CallOption) (*CalculateAmountResponse, error)
	GetAllOwners(ctx context.Context, in *GetAllOwnersRequest, opts ...grpc.CallOption) (*GetAllOwnersResponse, error)
	// Not Implemented
	GetVehicleOwnerDetails(ctx context.Context, in *VehicleOwnerDetailsRequest, opts ...grpc.CallOption) (*VehicleOwnerDetailsResponse, error)
	GetTollBoothDetails(ctx context.Context, in *TollBoothDetailsRequest, opts ...grpc.CallOption) (*VehicleOwnerDetailsResponse, error)
	CreateNewOwner(ctx context.Context, in *CreateNewOwnerRequest, opts ...grpc.CallOption) (*CreateNewOwnerResponse, error)
}

type tollTaxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTollTaxServiceClient(cc grpc.ClientConnInterface) TollTaxServiceClient {
	return &tollTaxServiceClient{cc}
}

func (c *tollTaxServiceClient) GenerateRFID(ctx context.Context, in *GenerateRFIDRequest, opts ...grpc.CallOption) (*GenerateRFIDResponse, error) {
	out := new(GenerateRFIDResponse)
	err := c.cc.Invoke(ctx, "/pb.TollTaxService/GenerateRFID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tollTaxServiceClient) ValidateRFID(ctx context.Context, in *ValidateRFIDRequest, opts ...grpc.CallOption) (*ValidateRFIDResponse, error) {
	out := new(ValidateRFIDResponse)
	err := c.cc.Invoke(ctx, "/pb.TollTaxService/ValidateRFID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tollTaxServiceClient) CalculateDeductibleAmount(ctx context.Context, in *CalculateAmountRequest, opts ...grpc.CallOption) (*CalculateAmountResponse, error) {
	out := new(CalculateAmountResponse)
	err := c.cc.Invoke(ctx, "/pb.TollTaxService/CalculateDeductibleAmount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tollTaxServiceClient) GetAllOwners(ctx context.Context, in *GetAllOwnersRequest, opts ...grpc.CallOption) (*GetAllOwnersResponse, error) {
	out := new(GetAllOwnersResponse)
	err := c.cc.Invoke(ctx, "/pb.TollTaxService/GetAllOwners", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tollTaxServiceClient) GetVehicleOwnerDetails(ctx context.Context, in *VehicleOwnerDetailsRequest, opts ...grpc.CallOption) (*VehicleOwnerDetailsResponse, error) {
	out := new(VehicleOwnerDetailsResponse)
	err := c.cc.Invoke(ctx, "/pb.TollTaxService/GetVehicleOwnerDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tollTaxServiceClient) GetTollBoothDetails(ctx context.Context, in *TollBoothDetailsRequest, opts ...grpc.CallOption) (*VehicleOwnerDetailsResponse, error) {
	out := new(VehicleOwnerDetailsResponse)
	err := c.cc.Invoke(ctx, "/pb.TollTaxService/GetTollBoothDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tollTaxServiceClient) CreateNewOwner(ctx context.Context, in *CreateNewOwnerRequest, opts ...grpc.CallOption) (*CreateNewOwnerResponse, error) {
	out := new(CreateNewOwnerResponse)
	err := c.cc.Invoke(ctx, "/pb.TollTaxService/CreateNewOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TollTaxServiceServer is the server API for TollTaxService service.
type TollTaxServiceServer interface {
	// Implemented
	GenerateRFID(context.Context, *GenerateRFIDRequest) (*GenerateRFIDResponse, error)
	ValidateRFID(context.Context, *ValidateRFIDRequest) (*ValidateRFIDResponse, error)
	CalculateDeductibleAmount(context.Context, *CalculateAmountRequest) (*CalculateAmountResponse, error)
	GetAllOwners(context.Context, *GetAllOwnersRequest) (*GetAllOwnersResponse, error)
	// Not Implemented
	GetVehicleOwnerDetails(context.Context, *VehicleOwnerDetailsRequest) (*VehicleOwnerDetailsResponse, error)
	GetTollBoothDetails(context.Context, *TollBoothDetailsRequest) (*VehicleOwnerDetailsResponse, error)
	CreateNewOwner(context.Context, *CreateNewOwnerRequest) (*CreateNewOwnerResponse, error)
}

// UnimplementedTollTaxServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTollTaxServiceServer struct {
}

func (*UnimplementedTollTaxServiceServer) GenerateRFID(context.Context, *GenerateRFIDRequest) (*GenerateRFIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateRFID not implemented")
}
func (*UnimplementedTollTaxServiceServer) ValidateRFID(context.Context, *ValidateRFIDRequest) (*ValidateRFIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateRFID not implemented")
}
func (*UnimplementedTollTaxServiceServer) CalculateDeductibleAmount(context.Context, *CalculateAmountRequest) (*CalculateAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateDeductibleAmount not implemented")
}
func (*UnimplementedTollTaxServiceServer) GetAllOwners(context.Context, *GetAllOwnersRequest) (*GetAllOwnersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllOwners not implemented")
}
func (*UnimplementedTollTaxServiceServer) GetVehicleOwnerDetails(context.Context, *VehicleOwnerDetailsRequest) (*VehicleOwnerDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVehicleOwnerDetails not implemented")
}
func (*UnimplementedTollTaxServiceServer) GetTollBoothDetails(context.Context, *TollBoothDetailsRequest) (*VehicleOwnerDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTollBoothDetails not implemented")
}
func (*UnimplementedTollTaxServiceServer) CreateNewOwner(context.Context, *CreateNewOwnerRequest) (*CreateNewOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNewOwner not implemented")
}

func RegisterTollTaxServiceServer(s *grpc.Server, srv TollTaxServiceServer) {
	s.RegisterService(&_TollTaxService_serviceDesc, srv)
}

func _TollTaxService_GenerateRFID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRFIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TollTaxServiceServer).GenerateRFID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TollTaxService/GenerateRFID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TollTaxServiceServer).GenerateRFID(ctx, req.(*GenerateRFIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TollTaxService_ValidateRFID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRFIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TollTaxServiceServer).ValidateRFID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TollTaxService/ValidateRFID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TollTaxServiceServer).ValidateRFID(ctx, req.(*ValidateRFIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TollTaxService_CalculateDeductibleAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateAmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TollTaxServiceServer).CalculateDeductibleAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TollTaxService/CalculateDeductibleAmount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TollTaxServiceServer).CalculateDeductibleAmount(ctx, req.(*CalculateAmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TollTaxService_GetAllOwners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllOwnersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TollTaxServiceServer).GetAllOwners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TollTaxService/GetAllOwners",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TollTaxServiceServer).GetAllOwners(ctx, req.(*GetAllOwnersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TollTaxService_GetVehicleOwnerDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VehicleOwnerDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TollTaxServiceServer).GetVehicleOwnerDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TollTaxService/GetVehicleOwnerDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TollTaxServiceServer).GetVehicleOwnerDetails(ctx, req.(*VehicleOwnerDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TollTaxService_GetTollBoothDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TollBoothDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TollTaxServiceServer).GetTollBoothDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TollTaxService/GetTollBoothDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TollTaxServiceServer).GetTollBoothDetails(ctx, req.(*TollBoothDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TollTaxService_CreateNewOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TollTaxServiceServer).CreateNewOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TollTaxService/CreateNewOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TollTaxServiceServer).CreateNewOwner(ctx, req.(*CreateNewOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TollTaxService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TollTaxService",
	HandlerType: (*TollTaxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateRFID",
			Handler:    _TollTaxService_GenerateRFID_Handler,
		},
		{
			MethodName: "ValidateRFID",
			Handler:    _TollTaxService_ValidateRFID_Handler,
		},
		{
			MethodName: "CalculateDeductibleAmount",
			Handler:    _TollTaxService_CalculateDeductibleAmount_Handler,
		},
		{
			MethodName: "GetAllOwners",
			Handler:    _TollTaxService_GetAllOwners_Handler,
		},
		{
			MethodName: "GetVehicleOwnerDetails",
			Handler:    _TollTaxService_GetVehicleOwnerDetails_Handler,
		},
		{
			MethodName: "GetTollBoothDetails",
			Handler:    _TollTaxService_GetTollBoothDetails_Handler,
		},
		{
			MethodName: "CreateNewOwner",
			Handler:    _TollTaxService_CreateNewOwner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tolltax.proto",
}
